export type Item = {
  type:string;
  attempts:number;
  run_after:string;
  locked_until:string;
  quantity: number;
  mentions?: string[];
  code: string;
  color: string;
  service_id: string;
  task_templates?: {name:string}[];
  avatar_path?: string;
  logo_path?: string;
  default_admin_id: string;
  enabled: boolean;
  endpoint_id: string;
  external_event_id: string;
  count: number;
  customer_name: string;
  contact_phone: string | null;
  contact_name: string | null;
  caller_id: string;
  deals: number;
  confirmed_sales: number;
  open_work: number;
  overdue_work: number;
  workload: { assignee_id: string; count: number }[];
  finance?: {
    receivable: number;
    payable: number;
    cash_net: number;
    cash_balance: number;
  };
  service_days: number;
  periods: { id: string; deal_id: string; start: string; end: string }[];
  plan_id: string;
  planned_count: number;
  completed_count: number;
  id: string;
  organization_id: string;
  name: string;
  title: string;
  serial: string;
  version: number;
  status: string;
  state: string;
  kind: string;
  stage: string;
  display_stage: string;
  pipeline: string;
  amount: number | null;
  commercial?: { total: number | null } | null;
  customer_id: string;
  deal_id: string;
  task_id: string;
  work_id: string;
  department_id: string;
  assignee_id: string;
  created_by: string;
  accountable_id: string;
  mediator_id: string;
  role_id: string;
  user_id: string;
  member_id: string;
  recipient_id: string;
  department_ids: string[];
  is_admin: boolean;
  overrides: Record<string, string>;
  permissions: string[];
  archived: boolean;
  due_at: string;
  due_date: string;
  starts_at: string;
  ends_at: string;
  first_confirmed_at: string;
  created_at: string;
  joined_at: string;
  read_at: string;
  body: string;
  label: string;
  email: string;
  phone: string;
  address: string;
  latitude: number | null;
  longitude: number | null;
  manual_pin: boolean;
  external_id: string;
  category: string;
  note: string;
  description: string;
  capacity: number;
  tool_id: string;
  unit_number: number;
  checked_out_at: string;
  returned_at: string;
  cancelled: boolean;
  url: string;
  location: string;
  agenda: string;
  outcome: string;
  conversation_id: string;
  author_id: string;
  actor_id: string;
  meeting_id: string;
  deleted: boolean;
  payment_date: string;
  direction: string;
  payment_id: string;
  document_id: string;
  account_id: string;
  reversed_payment_id: string;
  source_key: string;
  opening_amount: number;
  as_of: string;
  counterparty: string;
  reason: string;
  zero_reason: string;
  billing_day: number;
  first_payment_date: string;
  end_date: string;
  next_period_start: string;
  period_start: string;
  period_end: string;
  last_error: string;
  contract_id: string;
  settings: { works: Record<string, unknown>[]; accountable_id: string };
  cursor: number;
  mapping: Record<string, unknown>;
  file_hash: string;
  skills: string[];
  action: string;
  visibility: string;
  after_data: Record<string, unknown>;
  before_data: Record<string, unknown>;
};
export type WorkspaceData = Record<string, Item[]>;
