"use client";
import {useMemo, useState} from "react";
import {BarChart3, CalendarDays, Check, ChevronRight, Plus, Trash2, Users} from "lucide-react";
import type {Item} from "@/lib/db/types";
import type {PanelProps} from "@/components/module-page";
import {command} from "@/lib/db/api";
import {dateTime, localInput, utc} from "@/lib/domain";
import {Modal} from "@/components/dialog";
import {Field, Form, Select} from "@/components/form";

const categories=[['content_plan','Kontent plan'],['shooting','Çəkiliş'],['post_plan','Post plan'],['meta_manager','Meta Manager'],['design','Dizayn'],['copywriting','Copywriting'],['custom','Digər']] as const;
export function Marketing({org,data,member,refresh}:PanelProps){
 const [selected,setSelected]=useState<Item|null>(null),[add,setAdd]=useState(false),[addItem,setAddItem]=useState(false),[error,setError]=useState("");
 const plans=data.marketing_plans??[],items=data.marketing_plan_items??[],deals=data.deals??data.deal_cards??[];
 const active=plans.filter(p=>p.status!=="archived");
 const canManage=(p:Item)=>member.is_admin||p.created_by===member.id||deals.find(d=>d.id===p.deal_id)?.created_by===member.id||deals.find(d=>d.id===p.deal_id)?.accountable_id===member.id;
 const current=selected&&plans.find(p=>p.id===selected.id);
 const currentItems=current?items.filter(i=>i.plan_id===current.id&&!i.archived):[];
 const stats=useMemo(()=>{const total=currentItems.reduce((n,i)=>n+i.planned_count,0),done=currentItems.reduce((n,i)=>n+i.completed_count,0);return {total,done,pct:total?Math.round(done/total*100):0};},[currentItems]);
 const run=async(operation:string,payload:Record<string,unknown>,version=1)=>{try{setError("");await command(org,"marketing",operation,payload,version);await refresh();}catch(e){setError(e instanceof Error?e.message:"Əməliyyat alınmadı.");throw e;}};
 return <section className="marketing-page">{error&&<p className="notice error">{error}</p>}<div className="tasks-toolbar surface"><div><strong>Marketing plan</strong><p className="helper">Təsdiqlənmiş sifarişlər üzrə kontent, çəkiliş, post və reklam icrası.</p></div><button className="primary" onClick={()=>setAdd(true)}><Plus size={17}/> Plan yarat</button></div>
 <div className="marketing-grid">{active.map(plan=>{const rows=items.filter(i=>i.plan_id===plan.id&&!i.archived),count=rows.reduce((n,i)=>n+i.planned_count,0),done=rows.reduce((n,i)=>n+i.completed_count,0),pct=count?Math.round(done/count*100):0,deal=deals.find(d=>d.id===plan.deal_id);return <article className="surface marketing-card" key={plan.id}><div className="section-toolbar"><div><span className="badge">{pct}%</span><h2>{plan.title}</h2><p>{deal?.title||deal?.serial||"CRM qutusu"}</p></div><button onClick={()=>setSelected(plan)} aria-label="Planı aç"><ChevronRight/></button></div><div className="marketing-progress"><i style={{width:pct+"%"}}/></div><p><BarChart3 size={15}/>{done}/{count||0} plan vahidi tamamlanıb</p></article>})}</div>{!active.length&&<div className="empty">Hələ marketing plan yoxdur. Əvvəl CRM-də sifarişi təsdiqləyin, sonra plan yaradın.</div>}
 {add&&<PlanForm deals={deals} onClose={()=>setAdd(false)} onSave={async f=>{await run("plan.save",{deal_id:f.get("deal_id"),title:f.get("title")});setAdd(false);}}/>}
 {current&&<Modal title={current.title} wide onClose={()=>setSelected(null)}><div className="marketing-detail"><div className="marketing-summary"><div><span className="badge">{stats.pct}% tamamlanıb</span><h2>{stats.done} / {stats.total||0} vahid</h2><p>Qutu: {current.deal_id ? (deals.find(d=>d.id===current.deal_id)?.title||deals.find(d=>d.id===current.deal_id)?.serial) : "Hələ CRM qutusuna bağlanmayıb"}</p></div>{canManage(current)&&<div className="toolbar">{current.deal_id&&<button className="primary" onClick={()=>setAddItem(true)}><Plus size={16}/> Plan elementi</button>}<button className="danger" onClick={async()=>{await run("plan.archive",{id:current.id},current.version);setSelected(null);}}><Trash2 size={15}/>Sil</button></div>}</div><div className="marketing-progress large"><i style={{width:stats.pct+"%"}}/></div>{!current.deal_id&&member.is_admin&&<Form label="CRM qutusuna bağla" onSave={async f=>{await run("plan.save",{id:current.id,title:current.title,deal_id:f.get("deal_id")},current.version);await refresh();}}><Select name="deal_id" label="Təsdiqlənmiş CRM qutusu" options={deals.filter(d=>d.first_confirmed_at).map(d=>({id:d.id,name:d.title||d.serial}))} required/></Form>}<div className="stack">{currentItems.map(item=>{const assignee=data.memberships?.find(m=>m.id===item.assignee_id),allowed=canManage(current)||item.assignee_id===member.id;return <article className="work-row marketing-item" key={item.id}><div><span className="eyebrow">{categories.find(x=>x[0]===item.category)?.[1]||"Digər"}</span><h3>{item.title}</h3><p><Users size={14}/>{assignee?.name||"Təyinat yoxdur"} · <CalendarDays size={14}/>{dateTime(item.due_at)}</p></div><div className="toolbar"><strong>{item.completed_count}/{item.planned_count}</strong>{allowed&&<button onClick={async()=>{const value=prompt("Tamamlanan say",String(item.completed_count));if(value===null)return;const n=Number(value);if(!Number.isInteger(n)||n<0||n>item.planned_count){setError("0 ilə planlanan say arasında tam rəqəm yazın.");return;}await run("item.progress",{id:item.id,completed_count:n},item.version);}}>{item.status==="done"?<Check size={16}/>:"İrəliləyiş"}</button>}{canManage(current)&&<button title="Elementi sil" onClick={()=>run("item.archive",{id:item.id},item.version)}><Trash2 size={15}/></button>}</div></article>})}</div>{!currentItems.length&&<div className="empty">Plan elementi yoxdur.</div>}
 {addItem&&<ItemForm members={data.memberships??[]} departments={data.departments??[]} onClose={()=>setAddItem(false)} onSave={async f=>{await run("item.save",{plan_id:current.id,category:f.get("category"),title:f.get("title"),planned_count:Number(f.get("planned_count")),department_id:f.get("department_id"),assignee_id:f.get("assignee_id"),due_at:utc(f.get("due_at"))},current.version);setAddItem(false);}}/>}</div></Modal>}</section>;
}
function PlanForm({deals,onClose,onSave}:{deals:Item[];onClose:()=>void;onSave:(f:FormData)=>Promise<void>}){const confirmed=deals.filter(d=>d.first_confirmed_at);return <Modal title="Marketing plan yarat" onClose={onClose}><Form label="Planı yarat" onSave={onSave}><Select name="deal_id" label="CRM qutusu (istəyə bağlı)" options={confirmed.map(d=>({id:d.id,name:d.title||d.serial}))} empty="Sonra bağlayacağam"/><Field name="title" label="Planın adı" required/></Form><p className="helper">Qutu seçmədən yaradılan plan yalnız admin üçün görünür; qutuya bağlandıqdan sonra elementlər və To Do işləri əlavə edilə bilər.</p></Modal>}
function ItemForm({members,departments,onClose,onSave}:{members:Item[];departments:Item[];onClose:()=>void;onSave:(f:FormData)=>Promise<void>}){return <Modal title="Plan elementi əlavə et" onClose={onClose}><Form label="Əlavə et" onSave={onSave}><Select name="category" label="İş növü" options={categories.map(([id,name])=>({id,name}))} required/><Field name="title" label="İşin adı" required/><Field name="planned_count" label="Planlanan say" type="number" value={1} required/><Select name="department_id" label="Departament" options={departments.filter(d=>!d.archived).map(d=>({id:d.id,name:d.name}))} required/><Select name="assignee_id" label="Cavabdeh" options={members.filter(m=>m.status==="active").map(m=>({id:m.id,name:m.name}))} required/><Field name="due_at" label="Deadline" type="datetime-local" value={localInput(new Date().toISOString())} required/></Form></Modal>}
