-- Common archive operation for user-created operational records. Financial documents are intentionally excluded.
alter table public.tools add column if not exists created_by uuid references public.memberships(id), add column if not exists archived boolean not null default false;
alter table public.meetings add column if not exists archived boolean not null default false;
alter table public.conversations add column if not exists archived boolean not null default false;
alter table public.service_contracts add column if not exists created_by uuid references public.memberships(id), add column if not exists archived boolean not null default false;
update public.tools t set created_by=(select id from public.memberships m where m.organization_id=t.organization_id and m.is_admin and m.status='active' order by m.joined_at limit 1) where t.created_by is null;
update public.service_contracts c set created_by=(select id from public.memberships m where m.organization_id=c.organization_id and m.is_admin and m.status='active' order by m.joined_at limit 1) where c.created_by is null;

create function private.lifecycle_command(org uuid, operation text, payload jsonb, expected_version bigint, request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare m uuid:=private.require_member(org); rid uuid:=(payload->>'id')::uuid; kind text:=payload->>'kind'; prior private.requests; version_now bigint; owner uuid; result jsonb;
begin
 perform pg_advisory_xact_lock(hashtextextended(org::text,0));
 select * into prior from private.requests q where q.organization_id=org and q.actor_id=auth.uid() and q.request_id=lifecycle_command.request_id;
 if found then if prior.operation<>operation or prior.payload<>payload then raise exception 'IDEMPOTENCY_CONFLICT';end if;return prior.result;end if;
 if operation<>'archive' or kind not in('tool','meeting','conversation','resource_link','contract') then raise exception 'UNKNOWN_OPERATION';end if;
 if kind='tool' then select created_by,version into owner,version_now from public.tools where organization_id=org and id=rid for update; if owner is null then raise exception 'NOT_FOUND';end if; if not(private.is_admin(org) or owner=m) then raise exception 'OWNER_REQUIRED' using errcode='42501';end if; if version_now<>expected_version then raise exception 'VERSION_CONFLICT' using errcode='40001';end if; update public.tools set archived=true,version=version+1 where id=rid;
 elsif kind='meeting' then select created_by,version into owner,version_now from public.meetings where organization_id=org and id=rid for update; if owner is null then raise exception 'NOT_FOUND';end if; if not(private.is_admin(org) or owner=m) then raise exception 'OWNER_REQUIRED' using errcode='42501';end if; if version_now<>expected_version then raise exception 'VERSION_CONFLICT' using errcode='40001';end if; update public.meetings set archived=true,version=version+1 where id=rid;
 elsif kind='conversation' then select created_by,version into owner,version_now from public.conversations where organization_id=org and id=rid for update; if owner is null then raise exception 'NOT_FOUND';end if; if not(private.is_admin(org) or owner=m) then raise exception 'OWNER_REQUIRED' using errcode='42501';end if; if version_now<>expected_version then raise exception 'VERSION_CONFLICT' using errcode='40001';end if; update public.conversations set archived=true,version=version+1 where id=rid;
 elsif kind='resource_link' then select created_by,version into owner,version_now from public.resource_links where organization_id=org and id=rid for update; if owner is null then raise exception 'NOT_FOUND';end if; if not(private.is_admin(org) or owner=m) then raise exception 'OWNER_REQUIRED' using errcode='42501';end if; if version_now<>expected_version then raise exception 'VERSION_CONFLICT' using errcode='40001';end if; update public.resource_links set archived=true,version=version+1 where id=rid;
 else select created_by,version into owner,version_now from public.service_contracts where organization_id=org and id=rid for update; if owner is null then raise exception 'NOT_FOUND';end if; if not private.is_admin(org) then raise exception 'OWNER_REQUIRED' using errcode='42501';end if; if version_now<>expected_version then raise exception 'VERSION_CONFLICT' using errcode='40001';end if; update public.service_contracts set archived=true,version=version+1 where id=rid; end if;
 result:=jsonb_build_object('id',rid); insert into private.requests values(org,auth.uid(),request_id,operation,payload,result); insert into public.outbox_events(organization_id,topic,entity_id) values(org,'lifecycle',rid); return result;
end;$$;
create function public.lifecycle_command(org uuid,operation text,payload jsonb,expected_version bigint,request_id uuid) returns jsonb language sql security invoker set search_path='' as $$select private.lifecycle_command(org,operation,payload,expected_version,request_id);$$;
grant execute on function private.lifecycle_command(uuid,text,jsonb,bigint,uuid),public.lifecycle_command(uuid,text,jsonb,bigint,uuid) to authenticated;
